# Generated by Django 5.2.8 on 2025-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
